logging:
  version: 1
  disable_existing_loggers: true
  # Configuring the default (root) logger is highly recommended
  root:
    level: !!python/name:logging.NOTSET
    handlers: [console]
  loggers:
    # Logging from my application
    myapp.lib:
      level: !!python/name:logging.WARN
      handlers: [logfile]
      qualname: myapp.lib
      propagate: false
    myapp.cli:
      level: !!python/name:logging.WARN
      handlers: [console]
      qualname: myapp.cli
      propagate: false
    # Controlling logging of 3rd party libs
    sqlalchemy.engine:
      level: !!python/name:logging.WARN
      handlers: [logfile]
      qualname: sqlalchemy.engine
      propagate: false
    sqlalchemy.pool:
      level: !!python/name:logging.WARN
      handlers: [logfile]
      qualname: sqlalchemy.pool
      propagate: false
  handlers:
    logfile:
      class: logging.FileHandler
      filename: ../logs/sample.log
      formatter: simpleFormatter
      level: !!python/name:logging.NOTSET
    console:
      class: logging.StreamHandler
      stream: ext://sys.stdout
      formatter: simpleFormatter
      level: !!python/name:logging.NOTSET
  formatters:
    simpleFormatter:
      class: !!python/name:logging.Formatter
      format: '%(name)s %(asctime)s %(levelname)s %(message)s'
      datefmt: '%d/%m/%Y %H:%M:%S'